[build]
  publish = "blazedLabs/public"
  command = "cd blazedLabs && hugo --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.83.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://blazedlabs.com/"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
