// Code generated by Slice Machine. DO NOT EDIT.

import BrowseBlog from './BrowseBlog';
import Hero from './Hero';
import Image from './Image';
import ImageCards from './ImageCards';
import Quote from './Quote';
import Text from './Text';
import TextWithImage from './TextWithImage';

export {
	BrowseBlog,
	Hero,
	Image,
	ImageCards,
	Quote,
	Text,
	TextWithImage,
};

export const components = {
	browse_blog: BrowseBlog,
	hero: Hero,
	image: Image,
	image_cards: ImageCards,
	quote: Quote,
	text: Text,
	text_with_image: TextWithImage,
};
